### ISSUE TITLE
New-GitlabGroup's parameter '-ParentGroupName‘ is mandatory?

### ISSUE THREAD

**Issue by github2020-g** [chris-peterson/pwsh-gitlab#51]
Hi,

Thanks for your powershell module, it's very helpfull and effectively.

When I create a new group, I found the -ParentGroupName is mandatory, but 'get-help New-GitlabGroup -Full' is not mandatory.
------------------------------------------------------------
  -ParentGroupName <string>
        
        Required?                    false
------------------------------------------------------------
>new-GitlabGroup -GroupName test
**Exception: Unknown parent group (use -ParentGroupName)**
------------------------------------------------------------

Or it is my mistake?

Thanks

**Comment by chris-peterson** [comment]
That error is coming from [here](https://github.com/chris-peterson/pwsh-gitlab/blob/main/src/GitlabCli/Groups.psm1#L109)

`ParentGroupName` is indeed optional, and if not supplied, the code will attempt to infer the parent based on the current working directory.  If that's not working for you, it might be because you have a different directory structure than the remote layout

**Comment by github2020-g** [comment]
Dear,Thanks for your message.I will get back to you shortly.Have a good day!
Regards
Yueheng Guo

**Comment by chris-peterson** [comment]
Upon further reflection, this [behavior has been changed](https://github.com/chris-peterson/pwsh-gitlab/commit/211ac68d9dc7ac29fb959c67dfe8a4e725b7e057) -- `-ParentGroupName` is optional and won't have defaulting behavior.  To opt-in to the previous behavior of inferring parent based on current working directory, use the `.` convention

**Comment by chris-peterson** [comment]
Published in [`1.74.2`](https://www.powershellgallery.com/packages/GitlabCli/1.74.2)

**Comment by github2020-g** [comment]
Great! Thanks for your update and patiently.
